# Generated by Django 3.1.5 on 2021-02-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='sort_order',
            field=models.IntegerField(default=1),
        ),
    ]
