# Generated by Django 3.1.5 on 2021-02-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20210204_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='size',
            field=models.CharField(choices=[('img-small', 'Small'), ('img-large', 'Large')], default='img-large', max_length=10),
        ),
    ]
