# Generated by Django 3.1.5 on 2021-02-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20210208_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='size',
            field=models.CharField(choices=[('img-small', 'Small'), ('img-med', 'Medium'), ('img-large', 'Large')], default='img-large', max_length=10),
        ),
    ]
